# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  push:
    branches-ignore: ["ignore/*"]
  pull_request:
    branches-ignore: ["ignore/*"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      - name: Get current branch name
        id: branch_name
        run: |
          echo "BRANCH_NAME=$(echo $GITHUB_REF | sed 's/refs\/heads\///')" >> $GITHUB_ENV
      - name: Use branch name as a variable
        run: |
          echo "Current branch is '$BRANCH_NAME'"
  test:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org/"
      - name: Install pnpm
        run: |
          npm install -g pnpm
          pnpm install
      - name: Run unit tests
        run: pnpm test
